name: Build Arch Linux Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Update System
        run: |
          pacman -Syu --noconfirm

      - name: Install Dependencies
        run: |
          pacman -S --noconfirm base-devel git

      - name: Build Package
        run: |
          makepkg -s

      - name: Upload Package
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ./*.pkg.tar.*
